"""Export deliberation results to Markdown transcripts."""

from __future__ import annotations

from pathlib import Path

from civicarena.types import DeliberationResult, DQIScore, Stance

STANCE_LABELS = {
    Stance.STRONGLY_FOR: "Strongly For",
    Stance.FOR: "For",
    Stance.NEUTRAL: "Neutral",
    Stance.AGAINST: "Against",
    Stance.STRONGLY_AGAINST: "Strongly Against",
}


def export_markdown(result: DeliberationResult, output_path: str | Path) -> Path:
    """Write a deliberation result as a readable Markdown transcript.

    Returns the resolved path of the written file.
    """
    path = Path(output_path)
    lines: list[str] = []

    # Header
    lines.append(f"# CivicArena — {result.topic}")
    lines.append("")
    lines.append(f"**Location:** {result.location}")
    lines.append("")

    # Participants table
    lines.append("## Participants")
    lines.append("")
    lines.append("| Name | Age | Occupation | Initial Stance |")
    lines.append("|------|-----|------------|----------------|")
    for p in result.personas:
        stance = STANCE_LABELS.get(p.initial_stance, p.initial_stance.value)
        lines.append(f"| {p.name} | {p.age} | {p.occupation} | {stance} |")
    lines.append("")

    # Rounds
    for rnd in result.rounds:
        lines.append(f"## Round {rnd.round_number}: {rnd.round_name}")
        lines.append("")
        for stmt in rnd.statements:
            lines.append(f"### {stmt.persona_name}")
            lines.append("")
            lines.append(stmt.content)
            lines.append("")

    # Final votes
    lines.append("## Final Votes")
    lines.append("")
    lines.append("| Participant | Vote |")
    lines.append("|-------------|------|")
    for name, stance in result.final_votes.items():
        label = STANCE_LABELS.get(stance, stance.value)
        lines.append(f"| {name} | {label} |")
    lines.append("")

    # Vote tally
    tally: dict[str, int] = {}
    for stance in result.final_votes.values():
        label = STANCE_LABELS[stance]
        tally[label] = tally.get(label, 0) + 1

    lines.append("**Tally:**")
    for label, count in sorted(tally.items(), key=lambda x: -x[1]):
        lines.append(f"- {label}: {count}")
    lines.append("")

    # DQI Score
    if result.dqi_score:
        _append_dqi(lines, result.dqi_score)

    # Footer
    lines.append("---")
    lines.append("*Generated by [CivicArena](https://github.com/supratik-bhattacharya-2020/civic-arena)*")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path.resolve()


def _append_dqi(lines: list[str], score: DQIScore) -> None:
    """Append DQI score card to the markdown lines."""
    lines.append("## Deliberation Quality Score")
    lines.append("")
    lines.append("| Metric | Score | Max |")
    lines.append("|--------|-------|-----|")
    lines.append(f"| Justification | {score.justification_level} | 3 |")
    lines.append(f"| Respect | {score.respect} | 2 |")
    lines.append(f"| Constructive Politics | {score.constructive_politics} | 2 |")
    lines.append(f"| Overall Quality | {score.overall_quality} | 10 |")
    lines.append("")
    lines.append(f"**Summary:** {score.summary}")
    lines.append("")

    if score.highlights:
        lines.append("**Highlights:**")
        for h in score.highlights:
            lines.append(f"- {h}")
        lines.append("")

    if score.concerns:
        lines.append("**Areas for Improvement:**")
        for c in score.concerns:
            lines.append(f"- {c}")
        lines.append("")
